#
#
# Copyright (c) 2011, 2012
#   University of Houston System and Oak Ridge National Laboratory.
# 
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
# o Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# 
# o Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
# 
# o Neither the name of the University of Houston System, Oak Ridge
#   National Laboratory nor the names of its contributors may be used to
#   endorse or promote products derived from this software without specific
#   prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#

# TODO: make this a more decent makefile :)

all:
	@(cd accessibility; make)
	@(cd alloc; make)
	@(cd atomic; make)
	@(cd barrier; make)
	@(cd broadcast; make)
	@(cd collect; make)
	@(cd reductions; make)
	@(cd transfer; make)

clean:
	@(cd accessibility; make clean)
	@(cd alloc; make clean)
	@(cd atomic; make clean)
	@(cd barrier; make clean)
	@(cd broadcast; make clean)
	@(cd collect; make clean)
	@(cd reductions; make clean)
	@(cd transfer; make clean)

run:
	@(cd accessibility; make run)
	@(cd alloc; make run)
	@(cd atomic; make run)
	@(cd barrier; make run)
	@(cd broadcast; make run)
	@(cd collect; make run)
	@(cd reductions; make run)
	@(cd transfer; make run)
